/** ISO 3166-1 alpha-2, English name, country calling code (no +). */

export type CountryDialRow = {
  iso: string
  name: string
  dial: string
}

const RAW: CountryDialRow[] = [
  { iso: 'US', name: 'United States', dial: '1' },
  { iso: 'CA', name: 'Canada', dial: '1' },
  { iso: 'DO', name: 'Dominican Republic', dial: '1' },
  { iso: 'JM', name: 'Jamaica', dial: '1' },
  { iso: 'PR', name: 'Puerto Rico', dial: '1' },
  { iso: 'EG', name: 'Egypt', dial: '20' },
  { iso: 'ZA', name: 'South Africa', dial: '27' },
  { iso: 'GR', name: 'Greece', dial: '30' },
  { iso: 'NL', name: 'Netherlands', dial: '31' },
  { iso: 'BE', name: 'Belgium', dial: '32' },
  { iso: 'FR', name: 'France', dial: '33' },
  { iso: 'ES', name: 'Spain', dial: '34' },
  { iso: 'HU', name: 'Hungary', dial: '36' },
  { iso: 'IT', name: 'Italy', dial: '39' },
  { iso: 'RO', name: 'Romania', dial: '40' },
  { iso: 'CH', name: 'Switzerland', dial: '41' },
  { iso: 'AT', name: 'Austria', dial: '43' },
  { iso: 'GB', name: 'United Kingdom', dial: '44' },
  { iso: 'DK', name: 'Denmark', dial: '45' },
  { iso: 'SE', name: 'Sweden', dial: '46' },
  { iso: 'NO', name: 'Norway', dial: '47' },
  { iso: 'PL', name: 'Poland', dial: '48' },
  { iso: 'DE', name: 'Germany', dial: '49' },
  { iso: 'PE', name: 'Peru', dial: '51' },
  { iso: 'MX', name: 'Mexico', dial: '52' },
  { iso: 'CU', name: 'Cuba', dial: '53' },
  { iso: 'AR', name: 'Argentina', dial: '54' },
  { iso: 'BR', name: 'Brazil', dial: '55' },
  { iso: 'CL', name: 'Chile', dial: '56' },
  { iso: 'CO', name: 'Colombia', dial: '57' },
  { iso: 'VE', name: 'Venezuela', dial: '58' },
  { iso: 'MY', name: 'Malaysia', dial: '60' },
  { iso: 'AU', name: 'Australia', dial: '61' },
  { iso: 'ID', name: 'Indonesia', dial: '62' },
  { iso: 'PH', name: 'Philippines', dial: '63' },
  { iso: 'NZ', name: 'New Zealand', dial: '64' },
  { iso: 'SG', name: 'Singapore', dial: '65' },
  { iso: 'TH', name: 'Thailand', dial: '66' },
  { iso: 'JP', name: 'Japan', dial: '81' },
  { iso: 'KR', name: 'South Korea', dial: '82' },
  { iso: 'VN', name: 'Vietnam', dial: '84' },
  { iso: 'CN', name: 'China', dial: '86' },
  { iso: 'IN', name: 'India', dial: '91' },
  { iso: 'PK', name: 'Pakistan', dial: '92' },
  { iso: 'AF', name: 'Afghanistan', dial: '93' },
  { iso: 'LK', name: 'Sri Lanka', dial: '94' },
  { iso: 'MM', name: 'Myanmar', dial: '95' },
  { iso: 'IR', name: 'Iran', dial: '98' },
  { iso: 'SS', name: 'South Sudan', dial: '211' },
  { iso: 'MA', name: 'Morocco', dial: '212' },
  { iso: 'DZ', name: 'Algeria', dial: '213' },
  { iso: 'TN', name: 'Tunisia', dial: '216' },
  { iso: 'LY', name: 'Libya', dial: '218' },
  { iso: 'GM', name: 'Gambia', dial: '220' },
  { iso: 'SN', name: 'Senegal', dial: '221' },
  { iso: 'MR', name: 'Mauritania', dial: '222' },
  { iso: 'ML', name: 'Mali', dial: '223' },
  { iso: 'GN', name: 'Guinea', dial: '224' },
  { iso: 'CI', name: 'Ivory Coast', dial: '225' },
  { iso: 'BF', name: 'Burkina Faso', dial: '226' },
  { iso: 'NE', name: 'Niger', dial: '227' },
  { iso: 'TG', name: 'Togo', dial: '228' },
  { iso: 'BJ', name: 'Benin', dial: '229' },
  { iso: 'MU', name: 'Mauritius', dial: '230' },
  { iso: 'LR', name: 'Liberia', dial: '231' },
  { iso: 'SL', name: 'Sierra Leone', dial: '232' },
  { iso: 'GH', name: 'Ghana', dial: '233' },
  { iso: 'NG', name: 'Nigeria', dial: '234' },
  { iso: 'TD', name: 'Chad', dial: '235' },
  { iso: 'CF', name: 'Central African Republic', dial: '236' },
  { iso: 'CM', name: 'Cameroon', dial: '237' },
  { iso: 'CV', name: 'Cape Verde', dial: '238' },
  { iso: 'ST', name: 'São Tomé and Príncipe', dial: '239' },
  { iso: 'GQ', name: 'Equatorial Guinea', dial: '240' },
  { iso: 'GA', name: 'Gabon', dial: '241' },
  { iso: 'CG', name: 'Republic of the Congo', dial: '242' },
  { iso: 'CD', name: 'DR Congo', dial: '243' },
  { iso: 'AO', name: 'Angola', dial: '244' },
  { iso: 'GW', name: 'Guinea-Bissau', dial: '245' },
  { iso: 'IO', name: 'British Indian Ocean Territory', dial: '246' },
  { iso: 'AC', name: 'Ascension Island', dial: '247' },
  { iso: 'SC', name: 'Seychelles', dial: '248' },
  { iso: 'SD', name: 'Sudan', dial: '249' },
  { iso: 'RW', name: 'Rwanda', dial: '250' },
  { iso: 'ET', name: 'Ethiopia', dial: '251' },
  { iso: 'SO', name: 'Somalia', dial: '252' },
  { iso: 'DJ', name: 'Djibouti', dial: '253' },
  { iso: 'KE', name: 'Kenya', dial: '254' },
  { iso: 'TZ', name: 'Tanzania', dial: '255' },
  { iso: 'UG', name: 'Uganda', dial: '256' },
  { iso: 'BI', name: 'Burundi', dial: '257' },
  { iso: 'MZ', name: 'Mozambique', dial: '258' },
  { iso: 'ZM', name: 'Zambia', dial: '260' },
  { iso: 'MG', name: 'Madagascar', dial: '261' },
  { iso: 'RE', name: 'Réunion', dial: '262' },
  { iso: 'ZW', name: 'Zimbabwe', dial: '263' },
  { iso: 'NA', name: 'Namibia', dial: '264' },
  { iso: 'MW', name: 'Malawi', dial: '265' },
  { iso: 'LS', name: 'Lesotho', dial: '266' },
  { iso: 'BW', name: 'Botswana', dial: '267' },
  { iso: 'SZ', name: 'Eswatini', dial: '268' },
  { iso: 'KM', name: 'Comoros', dial: '269' },
  { iso: 'YT', name: 'Mayotte', dial: '269' },
  { iso: 'SH', name: 'Saint Helena', dial: '290' },
  { iso: 'ER', name: 'Eritrea', dial: '291' },
  { iso: 'AW', name: 'Aruba', dial: '297' },
  { iso: 'FO', name: 'Faroe Islands', dial: '298' },
  { iso: 'GL', name: 'Greenland', dial: '299' },
  { iso: 'GI', name: 'Gibraltar', dial: '350' },
  { iso: 'PT', name: 'Portugal', dial: '351' },
  { iso: 'LU', name: 'Luxembourg', dial: '352' },
  { iso: 'IE', name: 'Ireland', dial: '353' },
  { iso: 'IS', name: 'Iceland', dial: '354' },
  { iso: 'AL', name: 'Albania', dial: '355' },
  { iso: 'MT', name: 'Malta', dial: '356' },
  { iso: 'CY', name: 'Cyprus', dial: '357' },
  { iso: 'FI', name: 'Finland', dial: '358' },
  { iso: 'BG', name: 'Bulgaria', dial: '359' },
  { iso: 'LT', name: 'Lithuania', dial: '370' },
  { iso: 'LV', name: 'Latvia', dial: '371' },
  { iso: 'EE', name: 'Estonia', dial: '372' },
  { iso: 'MD', name: 'Moldova', dial: '373' },
  { iso: 'AM', name: 'Armenia', dial: '374' },
  { iso: 'BY', name: 'Belarus', dial: '375' },
  { iso: 'AD', name: 'Andorra', dial: '376' },
  { iso: 'MC', name: 'Monaco', dial: '377' },
  { iso: 'SM', name: 'San Marino', dial: '378' },
  { iso: 'UA', name: 'Ukraine', dial: '380' },
  { iso: 'RS', name: 'Serbia', dial: '381' },
  { iso: 'ME', name: 'Montenegro', dial: '382' },
  { iso: 'XK', name: 'Kosovo', dial: '383' },
  { iso: 'HR', name: 'Croatia', dial: '385' },
  { iso: 'SI', name: 'Slovenia', dial: '386' },
  { iso: 'BA', name: 'Bosnia and Herzegovina', dial: '387' },
  { iso: 'MK', name: 'North Macedonia', dial: '389' },
  { iso: 'CZ', name: 'Czech Republic', dial: '420' },
  { iso: 'SK', name: 'Slovakia', dial: '421' },
  { iso: 'LI', name: 'Liechtenstein', dial: '423' },
  { iso: 'BZ', name: 'Belize', dial: '501' },
  { iso: 'GT', name: 'Guatemala', dial: '502' },
  { iso: 'SV', name: 'El Salvador', dial: '503' },
  { iso: 'HN', name: 'Honduras', dial: '504' },
  { iso: 'NI', name: 'Nicaragua', dial: '505' },
  { iso: 'CR', name: 'Costa Rica', dial: '506' },
  { iso: 'PA', name: 'Panama', dial: '507' },
  { iso: 'PM', name: 'Saint Pierre and Miquelon', dial: '508' },
  { iso: 'HT', name: 'Haiti', dial: '509' },
  { iso: 'BO', name: 'Bolivia', dial: '591' },
  { iso: 'GY', name: 'Guyana', dial: '592' },
  { iso: 'EC', name: 'Ecuador', dial: '593' },
  { iso: 'GF', name: 'French Guiana', dial: '594' },
  { iso: 'PY', name: 'Paraguay', dial: '595' },
  { iso: 'MQ', name: 'Martinique', dial: '596' },
  { iso: 'SR', name: 'Suriname', dial: '597' },
  { iso: 'UY', name: 'Uruguay', dial: '598' },
  { iso: 'CW', name: 'Curaçao', dial: '599' },
  { iso: 'TL', name: 'Timor-Leste', dial: '670' },
  { iso: 'AQ', name: 'Antarctica', dial: '672' },
  { iso: 'BN', name: 'Brunei', dial: '673' },
  { iso: 'NR', name: 'Nauru', dial: '674' },
  { iso: 'PG', name: 'Papua New Guinea', dial: '675' },
  { iso: 'TO', name: 'Tonga', dial: '676' },
  { iso: 'SB', name: 'Solomon Islands', dial: '677' },
  { iso: 'VU', name: 'Vanuatu', dial: '678' },
  { iso: 'FJ', name: 'Fiji', dial: '679' },
  { iso: 'PW', name: 'Palau', dial: '680' },
  { iso: 'WF', name: 'Wallis and Futuna', dial: '681' },
  { iso: 'CK', name: 'Cook Islands', dial: '682' },
  { iso: 'NU', name: 'Niue', dial: '683' },
  { iso: 'WS', name: 'Samoa', dial: '685' },
  { iso: 'KI', name: 'Kiribati', dial: '686' },
  { iso: 'NC', name: 'New Caledonia', dial: '687' },
  { iso: 'TV', name: 'Tuvalu', dial: '688' },
  { iso: 'PF', name: 'French Polynesia', dial: '689' },
  { iso: 'TK', name: 'Tokelau', dial: '690' },
  { iso: 'FM', name: 'Micronesia', dial: '691' },
  { iso: 'MH', name: 'Marshall Islands', dial: '692' },
  { iso: 'KP', name: 'North Korea', dial: '850' },
  { iso: 'HK', name: 'Hong Kong', dial: '852' },
  { iso: 'MO', name: 'Macau', dial: '853' },
  { iso: 'KH', name: 'Cambodia', dial: '855' },
  { iso: 'LA', name: 'Laos', dial: '856' },
  { iso: 'BD', name: 'Bangladesh', dial: '880' },
  { iso: 'TW', name: 'Taiwan', dial: '886' },
  { iso: 'MV', name: 'Maldives', dial: '960' },
  { iso: 'LB', name: 'Lebanon', dial: '961' },
  { iso: 'JO', name: 'Jordan', dial: '962' },
  { iso: 'SY', name: 'Syria', dial: '963' },
  { iso: 'IQ', name: 'Iraq', dial: '964' },
  { iso: 'KW', name: 'Kuwait', dial: '965' },
  { iso: 'SA', name: 'Saudi Arabia', dial: '966' },
  { iso: 'YE', name: 'Yemen', dial: '967' },
  { iso: 'OM', name: 'Oman', dial: '968' },
  { iso: 'PS', name: 'Palestine', dial: '970' },
  { iso: 'AE', name: 'United Arab Emirates', dial: '971' },
  { iso: 'IL', name: 'Israel', dial: '972' },
  { iso: 'BH', name: 'Bahrain', dial: '973' },
  { iso: 'QA', name: 'Qatar', dial: '974' },
  { iso: 'BT', name: 'Bhutan', dial: '975' },
  { iso: 'MN', name: 'Mongolia', dial: '976' },
  { iso: 'NP', name: 'Nepal', dial: '977' },
  { iso: 'TJ', name: 'Tajikistan', dial: '992' },
  { iso: 'TM', name: 'Turkmenistan', dial: '993' },
  { iso: 'AZ', name: 'Azerbaijan', dial: '994' },
  { iso: 'GE', name: 'Georgia', dial: '995' },
  { iso: 'KG', name: 'Kyrgyzstan', dial: '996' },
  { iso: 'UZ', name: 'Uzbekistan', dial: '998' },
  { iso: 'KZ', name: 'Kazakhstan', dial: '7' },
  { iso: 'RU', name: 'Russia', dial: '7' },
]

function dialSortKey(dial: string): number {
  return parseInt(dial, 10)
}

/**
 * United States first, then all others sorted by numeric country code ascending, then name.
 */
export const COUNTRY_DIAL_OPTIONS: CountryDialRow[] = (() => {
  const us = RAW.find((r) => r.iso === 'US')
  const rest = RAW.filter((r) => r.iso !== 'US').sort((a, b) => {
    const da = dialSortKey(a.dial)
    const db = dialSortKey(b.dial)
    if (da !== db) return da - db
    return a.name.localeCompare(b.name, 'en')
  })
  return us ? [us, ...rest] : rest
})()

export function dialForIso(iso: string): string {
  const row = COUNTRY_DIAL_OPTIONS.find((r) => r.iso === iso)
  return row?.dial ?? '1'
}

/** Combine into E.164-style string for API + storage (e.g. +15551234567). */
export function combineInternationalPhone(iso: string, nationalDigits: string): string {
  const dial = dialForIso(iso)
  const n = nationalDigits.replace(/\D/g, '')
  return `+${dial}${n}`
}
